<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BaiHocSeeding extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate  = Carbon::create(2024, 10, 1);
        $endDate    = Carbon::create(2024, 12, 1);
        DB::table('bai_hocs')->delete();
        DB::table('bai_hocs')->truncate();
        DB::table('bai_hocs')->insert([
            // Khóa học 1: Fullstack Node.js Developer
            [
                'id_khoa_hoc'   => '1',
                'tieu_de'       => 'Giới thiệu về Node.js',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/ENrzD9HAZK4',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '1',
                'tieu_de'       => 'Cài đặt và cấu hình môi trường Node.js',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/TlB_eWDSMt4',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '1',
                'tieu_de'       => 'Xây dựng RESTful API với Express.js',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/L72fhGm1tfE',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '1',
                'tieu_de'       => 'Kết nối Node.js với MongoDB',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/ACUXjXtG8J4',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '1',
                'tieu_de'       => 'Triển khai ứng dụng Node.js lên Production',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/U8XF6AFGqlc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 2: React.js Master Class
            [
                'id_khoa_hoc'   => '2',
                'tieu_de'       => 'Giới thiệu về React.js',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Ke90Tje7VS0',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '2',
                'tieu_de'       => 'Sử dụng Hooks trong React',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/dpw9EHDh2bM',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '2',
                'tieu_de'       => 'Quản lý trạng thái với Context API',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/GE4jeED9B1s',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '2',
                'tieu_de'       => 'Sử dụng Redux cho quản lý trạng thái phức tạp',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/93p3LxR9xfM',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '2',
                'tieu_de'       => 'Best Practices trong React.js',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/f687hBjwFcM',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 3: Python cho Data Science
            [
                'id_khoa_hoc'   => '3',
                'tieu_de'       => 'Giới thiệu về Python cho Data Science',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/rfscVS0vtbw',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '3',
                'tieu_de'       => 'Xử lý dữ liệu với NumPy',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/8Mpc9ukltVA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '3',
                'tieu_de'       => 'Phân tích dữ liệu với Pandas',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/vmEHCJofslg',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '3',
                'tieu_de'       => 'Visualization dữ liệu với Matplotlib',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/UO98lJQ3QGI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '3',
                'tieu_de'       => 'Xử lý dữ liệu thực tế và Visualization',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/M7Ah3fHCSq8',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 4: AWS Cloud Practitioner
            [
                'id_khoa_hoc'   => '4',
                'tieu_de'       => 'Giới thiệu về AWS Cloud',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/3XFODda6YXo',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '4',
                'tieu_de'       => 'Các dịch vụ cơ bản của AWS',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Z3SYDTMP3ME',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '4',
                'tieu_de'       => 'Triển khai ứng dụng trên AWS EC2',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/_LIuNAu5Ktc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '4',
                'tieu_de'       => 'Quản lý cơ sở dữ liệu với AWS RDS',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/rM_c7K0-tC0',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '4',
                'tieu_de'       => 'Bảo mật và quản lý người dùng với AWS IAM',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/iF9fs8Rw4Uo',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 5: Flutter Mobile Development
            [
                'id_khoa_hoc'   => '5',
                'tieu_de'       => 'Giới thiệu về Flutter và Dart',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/fq4N0hgOWzU',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '5',
                'tieu_de'       => 'Tạo giao diện người dùng với Flutter Widgets',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/1gDhl4leEzA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '5',
                'tieu_de'       => 'Quản lý trạng thái trong Flutter',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/vU9xDLdEZtU',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '5',
                'tieu_de'       => 'Tạo responsive UI cho iOS và Android',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/x0uinJvhNxI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '5',
                'tieu_de'       => 'Triển khai ứng dụng Flutter lên App Store và Google Play',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/0zgDF81ZLrQ',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 6: Docker và Kubernetes
            [
                'id_khoa_hoc'   => '6',
                'tieu_de'       => 'Giới thiệu về Containerization với Docker',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/3c-iBn73dDE',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '6',
                'tieu_de'       => 'Tạo và quản lý Docker Images và Containers',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/pTFZFxd4hOI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '6',
                'tieu_de'       => 'Orchestration với Kubernetes: Cơ bản',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/X48VuDVv0do',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '6',
                'tieu_de'       => 'Triển khai Microservices với Kubernetes',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/PH-2FfFD2PU',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '6',
                'tieu_de'       => 'Quản lý và Scale ứng dụng trong Kubernetes',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/BUAFNfdarBQ',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 7: Angular Advanced
            [
                'id_khoa_hoc'   => '7',
                'tieu_de'       => 'Giới thiệu về Angular Framework',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/3qBXWUpoPHo',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '7',
                'tieu_de'       => 'Quản lý trạng thái với NgRx',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/kx0VTgTtSBg',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '7',
                'tieu_de'       => 'Lazy Loading Module trong Angular',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/htPYk6QxacQ',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '7',
                'tieu_de'       => 'Tối ưu hóa hiệu suất ứng dụng Angular',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/tMxrY7IL-Ac',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '7',
                'tieu_de'       => 'Best Practices trong Angular Development',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Fdf5aTYRW0E',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 8: Machine Learning Cơ Bản
            [
                'id_khoa_hoc'   => '8',
                'tieu_de'       => 'Giới thiệu về Machine Learning',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/GwIo3gDZCVQ',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '8',
                'tieu_de'       => 'Thuật toán Linear Regression',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/PaFP6a4-PXI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '8',
                'tieu_de'       => 'Thuật toán Decision Trees',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/eP1Aw9-RluE',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '8',
                'tieu_de'       => 'Sử dụng TensorFlow cho Machine Learning',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/tPYj3fFJGjk',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '8',
                'tieu_de'       => 'Ứng dụng thực tế của Machine Learning',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/aircAruvnKk',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 9: Golang Backend Development
            [
                'id_khoa_hoc'   => '9',
                'tieu_de'       => 'Giới thiệu về Go Language',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/YS4e4q9oBaU',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '9',
                'tieu_de'       => 'Xây dựng REST API với Go',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/1N8QqK1dP2s',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '9',
                'tieu_de'       => 'Quản lý cơ sở dữ liệu trong Go',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/CF9S8ClgG4Y',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '9',
                'tieu_de'       => 'Xây dựng Microservices với Go',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/No9C4x5DswU',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '9',
                'tieu_de'       => 'Triển khai ứng dụng Go lên Production',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/rt08HU9GcWc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 10: Unity Game Development
            [
                'id_khoa_hoc'   => '10',
                'tieu_de'       => 'Giới thiệu về Unity Engine',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/IlKaB1etrik',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '10',
                'tieu_de'       => 'Tạo game 2D đầu tiên với Unity',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/j48LtUkZRjU',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '10',
                'tieu_de'       => 'Phát triển game 3D với Unity',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/_QajrabyTJc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '10',
                'tieu_de'       => 'Tạo AI cho NPC trong game',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/SjV3nAy9gmc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '10',
                'tieu_de'       => 'Triển khai game hoàn chỉnh với Unity',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/2V1M_1fF6dY',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 11: MongoDB Advanced
            [
                'id_khoa_hoc'   => '11',
                'tieu_de'       => 'Giới thiệu về MongoDB',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/pWbMrx5rVBE',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '11',
                'tieu_de'       => 'Thiết kế Schema trong MongoDB',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/VBfU3m6f5b0',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '11',
                'tieu_de'       => 'Optimization truy vấn trong MongoDB',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/eBVXx5BFtHI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '11',
                'tieu_de'       => 'Scaling MongoDB trong Production',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/xx3dPZMgDcc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '11',
                'tieu_de'       => 'Bảo mật dữ liệu trong MongoDB',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/1vMaLPUX6_4',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 12: DevOps CI/CD
            [
                'id_khoa_hoc'   => '12',
                'tieu_de'       => 'Giới thiệu về DevOps và CI/CD',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/0fKg7e37bQE',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '12',
                'tieu_de'       => 'Thiết lập CI với Jenkins',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/TyGrtCb6HKk',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '12',
                'tieu_de'       => 'Thiết lập CI/CD với GitLab CI',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/h_6z8ABT1xE',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '12',
                'tieu_de'       => 'Thiết lập CI/CD với GitHub Actions',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Pq1NX8c-6nA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '12',
                'tieu_de'       => 'Tự động hóa quy trình phát triển và triển khai',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/CIoHdf3Wn8U',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 13: Cybersecurity Fundamentals
            [
                'id_khoa_hoc'   => '13',
                'tieu_de'       => 'Giới thiệu về An ninh mạng',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/3Kq1MIfTWCE',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '13',
                'tieu_de'       => 'Các loại Vulnerabilities phổ biến',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/C0DPdy98e4c',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '13',
                'tieu_de'       => 'Bảo vệ hệ thống khỏi các tấn công mạng',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/HG5XNpHFpPs',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '13',
                'tieu_de'       => 'Thiết lập firewall và hệ thống bảo mật',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/GejIDnVQaZo',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '13',
                'tieu_de'       => 'Best Practices trong Cybersecurity',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/0CRJPh8PH4s',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 14: SQL Master Course
            [
                'id_khoa_hoc'   => '14',
                'tieu_de'       => 'Giới thiệu về SQL',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/HXV3zeQKqGY',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '14',
                'tieu_de'       => 'Các câu lệnh cơ bản trong SQL',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/9Pzj7Aj25lw',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '14',
                'tieu_de'       => 'Advanced SQL Queries và Joins',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/9yeOJmtjV0Q',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '14',
                'tieu_de'       => 'Optimization và Performance Tuning trong SQL',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/oNIExY8M-6k',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '14',
                'tieu_de'       => 'Quản lý Transactions và Indexes',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/ZP7sjpQK4Mc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 15: GraphQL Advanced
            [
                'id_khoa_hoc'   => '15',
                'tieu_de'       => 'Giới thiệu về GraphQL',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/ed8SzALpx1Q',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '15',
                'tieu_de'       => 'Xây dựng Server với Apollo Server',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/y2YkccS7E-4',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '15',
                'tieu_de'       => 'Tạo Client với Apollo Client',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/sAgnJDJN4VA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '15',
                'tieu_de'       => 'Tối ưu hóa hiệu suất với GraphQL',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/As8il_wtEg0',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '15',
                'tieu_de'       => 'Best Practices trong GraphQL Development',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/tQ0jXLY1jxU',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 16: Swift iOS Development
            [
                'id_khoa_hoc'   => '16',
                'tieu_de'       => 'Giới thiệu về Swift và SwiftUI',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/comQ1-x2a1Q',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '16',
                'tieu_de'       => 'Xây dựng giao diện người dùng với SwiftUI',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/JIV7zB7X0u8',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '16',
                'tieu_de'       => 'Quản lý trạng thái và dữ liệu trong SwiftUI',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/1CfyQQyEymk',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '16',
                'tieu_de'       => 'Thiết kế UI/UX Patterns trong iOS',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/gZghNHMe8ic',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '16',
                'tieu_de'       => 'Best Practices trong Swift iOS Development',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/6F1sjwBsB2k',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 17: Blockchain Development
            [
                'id_khoa_hoc'   => '17',
                'tieu_de'       => 'Giới thiệu về Blockchain và Ethereum',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/3xGLc-zz9cA',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '17',
                'tieu_de'       => 'Phát triển Smart Contracts với Solidity',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/gyMwXuJrbJQ',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '17',
                'tieu_de'       => 'Xây dựng DApps với Web3.js',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/6mgbsDs5YFA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '17',
                'tieu_de'       => 'Tìm hiểu về DeFi và ứng dụng thực tế',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/0zj4e0E8ljo',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '17',
                'tieu_de'       => 'Bảo mật trong Blockchain Development',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Fy6M5cMpEo8',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 18: Flutter UI Masterclass
            [
                'id_khoa_hoc'   => '18',
                'tieu_de'       => 'Giới thiệu về Custom Widgets trong Flutter',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/5R-mRULzFVg',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '18',
                'tieu_de'       => 'Tạo Animations đẹp mắt với Flutter',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/sPIvVQHt1Cs',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '18',
                'tieu_de'       => 'Responsive Design trong Flutter',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/x0uinJvhNxI',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '18',
                'tieu_de'       => 'Sử dụng Themes và Styles trong Flutter',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/CEf-2H_fUVQ',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '18',
                'tieu_de'       => 'Best Practices cho UI/UX trong Flutter',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/GhQdlIFylQ8',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 19: Java Spring Boot
            [
                'id_khoa_hoc'   => '19',
                'tieu_de'       => 'Giới thiệu về Spring Boot',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/35EQXmHKZYs',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '19',
                'tieu_de'       => 'Dependency Injection trong Spring Boot',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/57xotwQn7fA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '19',
                'tieu_de'       => 'Bảo mật ứng dụng với Spring Security',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/1tB0d4pzbMc',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '19',
                'tieu_de'       => 'Xây dựng Microservices với Spring Boot',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/Jn0LMj3KhmM',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '19',
                'tieu_de'       => 'Triển khai Spring Boot Application lên Cloud',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/B03MItC4Yh4',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        
            // Khóa học 20: TypeScript Pro
            [
                'id_khoa_hoc'   => '20',
                'tieu_de'       => 'Giới thiệu về TypeScript',
                'bai_hoc_so'    => '1',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/BwuLxPH8IDs',
                'is_thu_phi'    => '0',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '20',
                'tieu_de'       => 'Advanced Types trong TypeScript',
                'bai_hoc_so'    => '2',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/zQnBQ4tB3ZA',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '20',
                'tieu_de'       => 'Sử dụng Decorators trong TypeScript',
                'bai_hoc_so'    => '3',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/vNqCeaB0W7U',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '20',
                'tieu_de'       => 'Áp dụng Design Patterns với TypeScript',
                'bai_hoc_so'    => '4',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/4yDkVYFc5SE',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
            [
                'id_khoa_hoc'   => '20',
                'tieu_de'       => 'Type Safety trong các dự án TypeScript',
                'bai_hoc_so'    => '5',
                'link_bai_hoc'  => 'https://www.youtube.com/embed/4B3rM4p2lb8',
                'is_thu_phi'    => '1',
                'tinh_trang'    => '1',
                'created_at' => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            ],
        ]);
        
    }
}
